hosts:
    vm-1:
        ip: 192.168.0.184
        services:
            - db
            - liferay
            - log-proxy
            - search
            - web-server
    vm-2:
        ip: 192.168.0.57
        services:
            - liferay
            - log-proxy
            - search
    vm-3:
        ip: 192.168.0.216
        services:
            - log-proxy
            - log-server
            - search
