#!/bin/bash

#
# Do NOT edit this file unless you are editing this file in the root directory
# of the the liferay-docker repository. Edit that file, and then fork it to the
# repository where it is used.
#

function lc_cd {
	if [ -d "${1}" ]
	then
		cd "${1}" || exit "${LIFERAY_COMMON_EXIT_CODE_CD}"
	else
		lc_log ERROR "${1} directory does not exist."

		exit "${LIFERAY_COMMON_EXIT_CODE_CD}"
	fi
}

function lc_check_utils {
	local exit_code=${LIFERAY_COMMON_EXIT_CODE_OK}

	for util in "${@}"
	do
		if (! command -v "${util}" &>/dev/null)
		then
			lc_log ERROR "The utility ${util} is not installed."

			exit_code="${LIFERAY_COMMON_EXIT_CODE_BAD}"
		fi
	done

	return "${exit_code}"
}

function lc_date {
	if [ -z ${1+x} ] || [ -z ${2+x} ]
	then
		if [ "$(uname)" == "Darwin" ]
		then
			/bin/date
		elif [ -e /bin/date ]
		then
			/bin/date --iso-8601=seconds
		else
			/usr/bin/date --iso-8601=seconds
		fi
	else
		if [ "$(uname)" == "Darwin" ]
		then
			/bin/date -jf "%a %b %e %H:%M:%S %Z %Y" "${1}" "${2}"
		elif [ -e /bin/date ]
		then
			/bin/date -d "${1}" "${2}"
		else
			/usr/bin/date -d "${1}" "${2}"
		fi
	fi
}

function lc_docker_compose {
	if [ -n "${LIFERAY_COMMON_DOCKER_COMPOSE}" ]
	then
		echo "${LIFERAY_COMMON_DOCKER_COMPOSE}"

		return
	fi

	local LIFERAY_COMMON_DOCKER_COMPOSE="docker compose"

	if (command -v docker-compose &>/dev/null)
	then
		LIFERAY_COMMON_DOCKER_COMPOSE="docker-compose"
	fi

	echo "${LIFERAY_COMMON_DOCKER_COMPOSE}"
}

# FUNCTION
#	Downloads a file to a cache directory configured via ${LIFERAY_COMMON_DOWNLOAD_CACHE_DIR}.
#	If the file is already in the cache then skip downloading it again.
#	If a file name is given as an optional second parameter, it is copied from the cache.
#	If the file cannot be downloaded in ${LIFERAY_COMMON_DOWNLOAD_MAX_TIME} seconds, the process is cancelled.
#
# INVOCATION:
#	lc_download <file url> [<destination file name>]
#
# EXIT CODES:
#	$LIFERAY_COMMON_EXIT_CODE_BAD: Missing argument or download failed.
#	$LIFERAY_COMMON_EXIT_CODE_OK: The file was downloaded and/or copied properly.

function lc_download {
	local file_url="${1}"

	if [ -z "${file_url}" ]
	then
		lc_log ERROR "File URL is not set."

		return "${LIFERAY_COMMON_EXIT_CODE_BAD}"
	fi

	local file_name="${2}"

	if [ -z "${file_name}" ]
	then
		file_name=${file_url##*/}
		skip_copy="true"
	fi

	if [ -e "${file_name}" ]
	then
		lc_log DEBUG "Not downloading '${file_url}' because it is already copied."

		echo "${file_name}"

		return
	fi

	local cache_file="${LIFERAY_COMMON_DOWNLOAD_CACHE_DIR}/${file_url##*://}"

	if [ -e "${cache_file}" ]
	then
		lc_log DEBUG "Not downloading the file because it already exists in the cache: '${cache_file}'."

		if [ "${skip_copy}" = "true" ]
		then
			lc_log DEBUG "Skipping copy."

			echo "${cache_file}"
		else
			lc_log DEBUG "Copying from cache: '${cache_file}'."

			cp "${cache_file}" "${file_name}"

			echo "${file_name}"
		fi

		return
	fi

	mkdir -p "$(dirname "${cache_file}")"

	lc_log DEBUG "Downloading '${file_url}'."

	local current_date=$(lc_date)

	local temp_suffix="temp_$(lc_date "${current_date}" "+%Y%m%d%H%M%S")"

	if (! curl "${file_url}" --fail --max-time "${LIFERAY_COMMON_DOWNLOAD_MAX_TIME}" --output "${cache_file}.${temp_suffix}" --show-error --silent)
	then
		lc_log ERROR "Unable to download '${file_url}'."

		return "${LIFERAY_COMMON_EXIT_CODE_BAD}"
	fi

	mv "${cache_file}.${temp_suffix}" "${cache_file}"

	if [ "${skip_copy}" = "true" ]
	then
		echo "${cache_file}"
	else
		lc_log DEBUG "Copying from cache: '${cache_file}'."

		cp "${cache_file}" "${file_name}"

		echo "${file_name}"
	fi
}

function lc_get_property {
	file=${1}
	property_key=${2}

	if [ "${file##*.}" == "bnd" ]
	then
		local property_value=$(grep -F "${property_key}: " "${file}")

		echo "${property_value##*: }"
	else
		local property_value=$(grep -F "${property_key}=" "${file}")

		echo "${property_value##*=}"
	fi
}

function lc_echo_time {
	local seconds=${1}

	printf "%02dh:%02dm:%02ds" $((seconds / 3600)) $((seconds % 3600 / 60)) $((seconds % 60))
}

function lc_log {
	local level="${1}"
	local message="${2}"

	if [ "${level}" != "DEBUG" ] || [ "${LIFERAY_COMMON_LOG_LEVEL}" == "DEBUG" ]
	then
		echo "$(lc_date) [${level}] ${message}" >&2
	fi
}

function lc_next_step {
	if [ -z "${LIFERAY_COMMON_STEP_FILE}" ]
	then
		LIFERAY_COMMON_STEP_FILE=$(mktemp)
	fi

	local step=$(cat "${LIFERAY_COMMON_STEP_FILE}")

	step=$((step + 1))

	echo ${step} > "${LIFERAY_COMMON_STEP_FILE}"

	printf "%02d" ${step}
}

function lc_time_run {
	local run_id=$(echo "${@}" | tr " /:" "_")
	local start_time=$(date +%s)

	if [ -n "${LIFERAY_COMMON_LOG_DIR}" ]
	then
		mkdir -p "${LIFERAY_COMMON_LOG_DIR}"

		local log_file="${LIFERAY_COMMON_LOG_DIR}/log_${LIFERAY_COMMON_START_TIME}_step_$(lc_next_step)_${run_id}.txt"
	fi

	echo "$(lc_date) > ${*}"

	if [ "${LIFERAY_COMMON_DEBUG_ENABLED}" != "true" ] && [ -n "${LIFERAY_COMMON_LOG_DIR}" ]
	then
		"${@}" &> "${log_file}"
	else
		"${@}"
	fi

	local exit_code=${?}

	local end_time=$(date +%s)

	if [ "${exit_code}" == "${LIFERAY_COMMON_EXIT_CODE_SKIPPED}" ]
	then
		echo -e "$(lc_date) < ${*}: \e[1;34mSkip\e[0m"

		return "${LIFERAY_COMMON_EXIT_CODE_SKIPPED}"
	else
		local seconds=$((end_time - start_time))

		if [ "${exit_code}" -gt 0 ]
		then
			echo -e "$(lc_date) ! ${*} exited with \e[1;31merror\e[0m in $(lc_echo_time ${seconds}) (exit code: ${exit_code})."

			if [ "${LIFERAY_COMMON_DEBUG_ENABLED}" != "true" ] && [ -n "${LIFERAY_COMMON_LOG_DIR}" ]
			then
				echo "Full log file is at ${log_file}. Printing the last 100 lines:"

				tail -n 100 "${log_file}"
			fi

			exit ${exit_code}
		else
			echo -e "$(lc_date) < ${*}: \e[1;32mSuccess\e[0m in $(lc_echo_time ${seconds})"
		fi
	fi
}

function _lc_init {
	LIFERAY_COMMON_START_TIME=$(date +%s)

	if [ -z "${LIFERAY_COMMON_DOWNLOAD_CACHE_DIR}" ]
	then
		LIFERAY_COMMON_DOWNLOAD_CACHE_DIR=${HOME}/.liferay-common-cache
	fi

	LIFERAY_COMMON_EXIT_CODE_BAD=1
	LIFERAY_COMMON_EXIT_CODE_CD=3
	LIFERAY_COMMON_EXIT_CODE_HELP=2
	LIFERAY_COMMON_EXIT_CODE_OK=0
	LIFERAY_COMMON_EXIT_CODE_SKIPPED=4
	LIFERAY_COMMON_DOWNLOAD_MAX_TIME=1200

	export LC_ALL=C
	export TZ=UTC
}

_lc_init